### PR TITLE
added the toto dog

### PR DESCRIPTION
**Pull request by brendalong**

### CODE REVIEW

**Review by Lunderwood33 — APPROVED** [review]
Looks awesome! Great work!

**Comment by ericfromspringfield1** [comment]
New dog. Who dis?

**Review by DArmstrong87 — APPROVED** [review]
The goodest boi has joined the chat. Looks great!

**Review by Scott47 — APPROVED** [review]
👍 looks great! ready for merge.

**Comment by Scott47** [comment]
👍 looks

**Pull request merged**
